### ISSUE TITLE
Fileupload failed

### ISSUE THREAD

**Issue by dgram** [directus/sdk-js#134]
# 🐞 Bug report

### Description
I've got the same error as described in #78 for my node FormData Upload. 
So i try to upload files via directus-sdk-js on my node server and got the message ```Missing boundary in multipart/form-data POST data ````

## 🔬 Minimal Reproduction
```ts
import * as FormData from 'form-data';
import SDK from '@directus/sdk-js';

const sdk = new SDK({...});
let data = new FormData();
// image.content = Buffer
data.append('file', image.content, image.filename);

try {               
    let upload = await sdk.uploadFiles(data);
} catch (e) {
    console.log(e)
}
```

## 🔥 Exception or Error
***PHP Server Warning***
<pre><code>
 Missing boundary in multipart/form-data POST data in <b>Unknown</b>
</code></pre>

***Directus Exception***
<pre><code>
[2020-01-27 21:28:45] api[Marketing].ERROR: Directus\Validator\Exception\InvalidRequestException: data: This value should not be blank. filename_disk: This value should not be blank. filename_download: This value should not be blank. in D:\directus\src\core\Directus\Services\AbstractService.php:186
Stack trace:
#0 D:\directus\src\core\Directus\Services\AbstractService.php(120): Directus\Services\AbstractService->throwErrorIfAny
#1 D:\directus\src\core\Directus\Services\FilesServices.php(48): Directus\Services\AbstractService->validate
#2 D:\directus\src\endpoints\Files.php(75): Directus\Services\FilesServices->create
#3 [internal function]: Directus\Api\Routes\Files->create
#4 D:\directus\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(40): call_user_func
#5 D:\directus\vendor\slim\slim\Slim\Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke
#6 D:\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\Route->__invoke
#7 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#8 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#9 [internal function]: Slim\DeferredCallable->__invoke
#10 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#11 D:\directus\src\core\Directus\Application\Http\Middleware\AuthenticationMiddleware.php(124): Slim\Route->Slim\{closure}
#12 [internal function]: Directus\Application\Http\Middleware\AuthenticationMiddleware->__invoke
#13 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#14 [internal function]: Slim\DeferredCallable->__invoke
#15 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#16 D:\directus\src\core\Directus\Application\Http\Middleware\TableGatewayMiddleware.php(25): Slim\Route->Slim\{closure}
#17 [internal function]: Directus\Application\Http\Middleware\TableGatewayMiddleware->__invoke
#18 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#19 [internal function]: Slim\DeferredCallable->__invoke
#20 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#21 D:\directus\src\core\Directus\Application\Http\Middleware\DatabaseMigrationMiddleware.php(15): Slim\Route->Slim\{closure}
#22 [internal function]: Directus\Application\Http\Middleware\DatabaseMigrationMiddleware->__invoke
#23 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#24 [internal function]: Slim\DeferredCallable->__invoke
#25 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#26 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}
#27 D:\directus\vendor\slim\slim\Slim\Route.php(268): Slim\Route->callMiddlewareStack
#28 D:\directus\vendor\slim\slim\Slim\App.php(503): Slim\Route->run
#29 D:\directus\src\core\Directus\Application\Http\Middleware\AbstractRateLimitMiddleware.php(34): Slim\App->__invoke
#30 [internal function]: Directus\Application\Http\Middleware\AbstractRateLimitMiddleware->__invoke
#31 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#32 [internal function]: Slim\DeferredCallable->__invoke
#33 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#34 D:\directus\vendor\directus\proxy-detection\src\ProxyDetectionMiddleware.php(30): Slim\App->Slim\{closure}
#35 D:\directus\src\core\Directus\Application\Http\Middleware\ProxyMiddleware.php(18): RKA\Middleware\ProxyDetectionMiddleware->__invoke
#36 [internal function]: Directus\Application\Http\Middleware\ProxyMiddleware->__invoke
#37 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#38 [internal function]: Slim\DeferredCallable->__invoke
#39 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#40 D:\directus\vendor\akrabat\ip-address-middleware\src\IpAddress.php(113): Slim\App->Slim\{closure}
#41 [internal function]: RKA\Middleware\IpAddress->__invoke
#42 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#43 [internal function]: Slim\DeferredCallable->__invoke
#44 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#45 D:\directus\src\core\Directus\Application\Http\Middleware\CorsMiddleware.php(71): Slim\App->Slim\{closure}
#46 [internal function]: Directus\Application\Http\Middleware\CorsMiddleware->__invoke
#47 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#48 [internal function]: Slim\DeferredCallable->__invoke
#49 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#50 D:\directus\src\core\Directus\Application\Http\Middleware\ResponseCacheMiddleware.php(62): Slim\App->Slim\{closure}
#51 [internal function]: Directus\Application\Http\Middleware\ResponseCacheMiddleware->__invoke
#52 D:\directus\vendor\slim\slim\Slim\DeferredCallable.php(57): call_user_func_array
#53 [internal function]: Slim\DeferredCallable->__invoke
#54 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func
#55 D:\directus\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}
#56 D:\directus\vendor\slim\slim\Slim\App.php(392): Slim\App->callMiddlewareStack
#57 D:\directus\vendor\slim\slim\Slim\App.php(297): Slim\App->process
#58 D:\directus\src\core\Directus\Application\Application.php(161): Slim\App->run
#59 D:\directus\public\index.php(4): Directus\Application\Application->run [] []
</code></pre>

## 🌍 Your Environment

**SDK Version:** ```v6.0.0```
**Directus Version:** ```v8.4.0```
**PHP-Version:** ```7.3.9```

**Comment by rijkvanzanten** [comment]
I think this is caused by the fact that the headers don't contain the correct boundary in this case. As per https://www.npmjs.com/package/form-data#axios, we should add a way to override the headers for this specific request so you can use `const formHeaders = form.getHeaders();` to pass it the header with the correct boundary
